---
- hosts: all
  remote_user: ansible

  tasks:

    - name: Check Splunk process running
      shell: "ps -ef | grep splunk | grep -v grep"
      register: result
      ignore_errors: true

    - debug:
        var: result.stdout_lines
