---
<<<<<<< HEAD
- hosts: {{umounthost}}
=======
- hosts: app01
>>>>>>> 00f3deb87d8b5f1c7e17d44ef30a139bf55e9e64
  remote_user: ansible

  tasks:

    name: Stop transmission container
    docker_container:
      name: transmission-daemon
      state: stopped

    name: Stop sickrage container
    docker_container:
      name: sickrage
      state: stopped

    name: Stop couchpotato container
    docker_container:
      name: couchpotato
      state: stopped

    name: Unmount hard drive from app01
    mount:
      path: /mnt/hdd1
      state: unmounted

    name: Waiting 15 secs
    pause: seconds=15

    name: Mount hard drive to app01
    mount:
      path: /mnt/hdd1
      src: app00:/mnt/hdd1
      state: mounted

    name: Start transmission container
    docker_container:
      name: transmission-daemon
      state: started

    name: Start couchpotato container
    docker_container:
      name: couchpotato
      state: started

    name: Start sickrage container
    docker_container:
      name: sickrage
      state: started
